### PR TITLE
Added Salalem :)

### PR DESCRIPTION
**Pull request by firaskafri**

### CODE REVIEW

**Comment by waldyrious** [comment]
@firasalkafri Hi, sorry for the delay -- this project is currently kind of stagnant, unfortunately.

I'm not sure about the joining process for the OCI itself (see #130 and #103) and appearing in the website. I suppose the explicit instructions are those at http://www.opencompany.org/join/, but @galuszkak might be able to give you a more definitive answer.

In the meantime, I'd strongly suggest you to send a PR to the https://github.com/opencompany/awesome-open-company repo (which might eventually become the canonical list for the OCI, providing a simpler and more maintainable infrastructure for this project).

**Comment by galuszkak** [comment]
@waldyrious @firasalkafri I can fix build next week.

**Comment by galuszkak** [comment]
Build is fixed today. We can merge this now!

**Comment by waldyrious** [comment]
Yay @galuszkak! 👏

I'm still wondering about the "formal" process for joining, though. According to the discussion in #130, it seems like we still assume that dues should be paid (even if the value itself is left at the discretion of each member); in particular, quoting @chadwhitacre from that thread:

> Then "joining" would simply mean giving on Gratipay.

> Conversely, "leaving" would mean not giving anymore.

I'm not sure Liberapay allows access to who the patrons are; without that, there's no way to verify the above conditions. @changaco, can you providfe any insight here?

In any case, none of the members listed on the website are paying any dues; Our Liberapay profile indicates that there's a single donor, and [that's the previous Gratipay balance](https://github.com/opencompany/www.opencompany.org/issues/175#issuecomment-445960061). So it would be unfair to require this from new members. Maybe we should make it clear that membership dues can be zero? That would resolve the issue.

**Comment by waldyrious** [comment]
That said, we also ought to consider if we should follow the process currently listed at http://www.opencompany.org/join/, i.e. that new members should provide the following info:

>- Your name and title;
>- The name of your company;
>- A link to your homepage, or a landing page about openness;
>- A logo file in SVG format;
>- A one-line description of your company;
>- One concrete example of how your company already fulfills our pledge.

We're missing the logo and the example of how the company fulfills the OCI pledge, so technically the PR can't be merged as-is (unless we decide to change the rules).

Of course, the attentive will notice that this process pretty much duplicates [the one](https://github.com/opencompany/awesome-open-company/wiki/Inclusion+guidelines) for adding entries to the [awesome-open-company](https://github.com/opencompany/awesome-open-company) list. Due to the clear lack of manpower we currently have, we should seriously consider merging the two. WDYT, @galuszkak?

**Comment by Changaco** [comment]
@waldyrious Donations are anonymous on Liberapay, as they were on Gratipay. It may change in the future, but I haven't started working on it yet (<https://github.com/liberapay/liberapay.com/issues/271>).

Sorry about the late reply.

**Comment by waldyrious** [comment]
No problem at at all, @Changaco, thanks for the info!

So that's one more reason to remove the due-paying condition from the list of what constitutes an OCI member.

**Pull request merged**
